# Base Image for LLM Dependencies
FROM python:3.11.3

LABEL maintainer="mkaragiannop@juniper.net"

# Update and install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gcc python3-dev libffi-dev libssl-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
